### ISSUE TITLE
alt attribute

### ISSUE THREAD

**Issue by gdedi001** [jridley11/prj-rev-bwfs-dasmoto#3]
Dont forget to add the `alt` attribute to your image tags here
https://github.com/jridley11/prj-rev-bwfs-dasmoto/blob/master/Dasmoto'sArts%26Crafts/index.html#L12

**Comment by jridley11** [comment]
Could you please explain a little more regarding this as I have reviewed the notes regarding images (section 8 of the HTML Tags lesson) and can't find anything regarding the alt attribute? It only mentions the following:

"The <img> tag has a required attribute called src. The src attribute must be set to the image's source, or the location of the image."
